import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { App as AntApp, Alert, Button, Card, ConfigProvider, Empty, Form, Input, Layout, List, Popconfirm, Select, Skeleton, Space, Steps, Tag, Typography, message } from 'antd'
import { api, McpServer, Orchestration, Skill, SkillPreview, Template, Worker, WorkflowEvent } from './api'
import { ApiOutlined, BookOutlined, DeleteOutlined, FileTextOutlined, PlayCircleOutlined, PlusOutlined, TeamOutlined, UnorderedListOutlined } from '@ant-design/icons'
import './styles.css'

const { Header, Content, Sider } = Layout

function Status({ value }: { value: string }) {
  const color: Record<string, string> = { completed: 'green', running: 'blue', queued: 'gold', failed: 'red', cancelled: 'default', needs_approval: 'orange' }
  return <Tag color={color[value] ?? 'default'}>{value}</Tag>
}

function Workers() {
  const [workers, setWorkers] = useState<Worker[]>(); const [notice, contextHolder] = message.useMessage()
  const refresh = () => api.workers().then(setWorkers).catch(() => setWorkers([]))
  useEffect(() => { void refresh() }, [])
  const remove = async (worker: Worker) => { try { await api.deleteWorker(worker.worker_id); notice.success('员工已删除'); refresh() } catch (error) { notice.error(error instanceof Error ? error.message : '删除失败') } }
  if (!workers) return <Skeleton active />
  return <>{contextHolder}<div className="page-heading"><div><Typography.Title level={2}>数字员工目录</Typography.Title><Typography.Text type="secondary">已注册的可编排能力与作业规范</Typography.Text></div><Link to="/tasks/new"><Button type="primary" icon={<PlayCircleOutlined />}>发起协作</Button></Link></div><div className="worker-grid">{workers.map(worker => <Card key={worker.worker_id} className="worker-card" title={<Space><TeamOutlined /><span>{worker.name}</span></Space>} extra={<Space><Status value={worker.enabled ? 'completed' : 'disabled'} />{worker.editable && <Link to={`/admin/workers/${worker.worker_id}/edit`}>编辑</Link>}{worker.editable && <Popconfirm title="删除该员工？此操作不可恢复。" onConfirm={() => remove(worker)}><Button type="link" danger>删除</Button></Popconfirm>}</Space>}><Typography.Paragraph>{worker.description}</Typography.Paragraph><Typography.Text type="secondary">{worker.worker_id} · {worker.runtime_name}</Typography.Text><div className="tag-row">{worker.capabilities.map(item => <Tag key={item} color="cyan">{item}</Tag>)}</div>{worker.mcp_tools.length > 0 && <div className="skill-line"><Typography.Text type="secondary">MCP</Typography.Text>{worker.mcp_tools.map(name => <Tag key={name} color="purple">{name}</Tag>)}</div>}{worker.skill_catalog.length > 0 && <div className="skill-line"><Typography.Text type="secondary">Skill</Typography.Text>{worker.skill_catalog.map(item => <Tag key={item.name} color="geekblue">{item.name}</Tag>)}</div>}</Card>)}</div></>
}

function NewTask() {
  const navigate = useNavigate(); const [templates, setTemplates] = useState<Template[]>([]); const [workers, setWorkers] = useState<Worker[]>([]); const [selected, setSelected] = useState<string>(); const [submitting, setSubmitting] = useState(false); const [form] = Form.useForm(); const [notice, contextHolder] = message.useMessage()
  useEffect(() => { api.templates().then(setTemplates); api.workers().then(setWorkers) }, [])
  const submit = async (values: { goal: string; mode: string; worker_ids: string[] }) => { setSubmitting(true); try { const created = await api.create({ ...values, template_id: selected }); navigate(`/tasks/${created.orchestration_id}`) } catch (error) { notice.error(error instanceof Error ? error.message : '创建失败') } finally { setSubmitting(false) } }
  const choose = (id: string) => { const template = templates.find(item => item.id === id); setSelected(id); if (template) form.setFieldsValue({ mode: template.mode, worker_ids: template.worker_ids }) }
  return <><div className="page-heading"><div><Typography.Title level={2}>发起协作任务</Typography.Title><Typography.Text type="secondary">选择编排模板或自定义参与员工</Typography.Text></div></div>{contextHolder}<div className="compose-layout"><section><Typography.Title level={4}>内置场景</Typography.Title><Space direction="vertical" className="template-stack">{templates.map(item => <Card key={item.id} className={selected === item.id ? 'template active' : 'template'} onClick={() => choose(item.id)}><Typography.Text strong>{item.name}</Typography.Text><br /><Typography.Text type="secondary">{item.mode} · {item.worker_ids.join(' → ')}</Typography.Text></Card>)}</Space></section><Card className="form-panel"><Form form={form} layout="vertical" initialValues={{ mode: 'sequential', worker_ids: [] }} onFinish={submit}><Form.Item name="goal" label="协作目标" rules={[{ required: true, message: '请输入目标' }]}><Input.TextArea rows={5} placeholder="例如：调研 A 公司近一年动态并形成事实速览" /></Form.Item><Form.Item name="mode" label="编排模式"><Select options={[['sequential', '顺序协作'], ['concurrent', '并行协作'], ['handoff', '接力协作'], ['react', 'REACT 反思循环']].map(([value, label]) => ({ value, label }))} disabled={Boolean(selected)} /></Form.Item><Form.Item name="worker_ids" label="参与员工" rules={[{ required: true, message: '至少选择一名员工' }]}><Select mode="multiple" options={workers.filter(item => item.enabled).map(item => ({ value: item.worker_id, label: `${item.name} (${item.worker_id})` }))} disabled={Boolean(selected)} /></Form.Item><Button htmlType="submit" type="primary" size="large" loading={submitting} icon={<PlayCircleOutlined />}>开始执行</Button></Form></Card></div></>
}

function TaskDetail() {
  const { id = '' } = useParams(); const [run, setRun] = useState<Orchestration>(); const [events, setEvents] = useState<WorkflowEvent[]>([]); const [error, setError] = useState<string>(); const [notice, contextHolder] = message.useMessage()
  useEffect(() => { let source: EventSource | undefined; const load = async () => { try { setRun(await api.run(id)); source = new EventSource(`/api/orchestrations/${id}/events`); for (const name of ['plan', 'task_dispatch', 'task_receipt', 'approval_required', 'approval_resolved', 'aggregate', 'failed']) source.addEventListener(name, event => { const item = JSON.parse((event as MessageEvent).data) as WorkflowEvent; setEvents(current => [...current.filter(existing => existing.seq !== item.seq), item]); api.run(id).then(setRun) }); source.onerror = () => setError('实时连接已中断，正在等待浏览器重连') } catch (cause) { setError(cause instanceof Error ? cause.message : '加载失败') } }; load(); return () => source?.close() }, [id])
  if (error) return <Empty description={error} />; if (!run) return <Skeleton active />
  const results = run.result?.worker_results ?? []
  const approval = events.find(item => item.type === 'approval_required')
  const decide = async (decision: 'approve' | 'reject') => { if (!approval?.payload.task_id) return; try { await api.approve(id, approval.payload.task_id, decision, '前端审批'); notice.success(decision === 'approve' ? '已批准，正在恢复执行' : '已驳回') } catch (cause) { notice.error(cause instanceof Error ? cause.message : '审批失败') } }
  return <>{contextHolder}<div className="page-heading"><div><Typography.Title level={2}>协作执行</Typography.Title><Typography.Text type="secondary">{run.orchestration_id}</Typography.Text></div><Space><Link to={`/tasks/${id}/continue`}><Button>继续任务</Button></Link><Status value={run.status} /></Space></div><Card className="goal-card"><Typography.Text type="secondary">目标</Typography.Text><Typography.Title level={4}>{run.goal}</Typography.Title><Tag>{run.mode}</Tag><Tag color="blue">{run.session_id}</Tag></Card>{run.status === 'waiting_approval' && approval && <Alert className="approval-alert" type="warning" showIcon message={`等待 ${approval.payload.worker_id} 的人工审批`} description={<Space><Button type="primary" onClick={() => decide('approve')}>批准并继续</Button><Button onClick={() => decide('reject')}>驳回</Button></Space>} />}<section className="timeline-section"><Typography.Title level={4}>实时执行轨迹</Typography.Title><Steps direction="vertical" size="small" current={events.length} items={events.filter(item => item.type !== 'heartbeat').map(item => ({ title: `${item.type}${item.payload.worker_id ? ` · ${item.payload.worker_id}` : ''}`, description: item.payload.instruction ?? item.payload.status ?? item.payload.error ?? `事件 #${item.seq}` }))} /></section>{results.length > 0 && <Card title="任务回执" className="result-card"><Steps direction="vertical" size="small" items={results.map(result => ({ title: `${result.worker_id} · ${result.status}`, description: result.output?.text ?? '等待回执' }))} /></Card>}{run.result && <Card title="聚合结论" className="result-card"><Typography.Paragraph>{run.result.summary}</Typography.Paragraph></Card>}<Card title="会话审计" className="session-card"><List size="small" locale={{ emptyText: '任务完成后显示会话记录' }} dataSource={run.session?.messages ?? []} renderItem={item => <List.Item>{item}</List.Item>} /></Card></>
}

function ContinueTask() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [run, setRun] = useState<Orchestration>(); const [workers, setWorkers] = useState<Worker[]>([]); const [form] = Form.useForm(); const [notice, contextHolder] = message.useMessage(); const [submitting, setSubmitting] = useState(false)
  useEffect(() => { api.run(id).then(item => { setRun(item); form.setFieldsValue({ mode: item.mode, worker_ids: item.effective.worker_ids }) }).catch(error => notice.error(error instanceof Error ? error.message : '加载历史任务失败')); api.workers().then(setWorkers) }, [form, id, notice])
  const submit = async (values: { goal: string; mode: string; worker_ids: string[] }) => { setSubmitting(true); try { const created = await api.continueRun(id, values); navigate(`/tasks/${created.orchestration_id}`) } catch (error) { notice.error(error instanceof Error ? error.message : '续办失败') } finally { setSubmitting(false) } }
  if (!run) return <Skeleton active />
  return <>{contextHolder}<div className="page-heading"><div><Typography.Title level={2}>继续历史任务</Typography.Title><Typography.Text type="secondary">复用原会话和已有上下文；可调整参与员工后处理新的用户请求。</Typography.Text></div><Link to={`/tasks/${id}`}><Button>返回任务</Button></Link></div><Card className="worker-form"><Typography.Paragraph type="secondary">原任务：{run.goal}</Typography.Paragraph><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="goal" label="新的请求" rules={[{ required: true, message: '请输入需要继续处理的内容' }]}><Input.TextArea rows={5} placeholder="例如：基于前面的结果补充风险分析，并输出给管理层的结论。" /></Form.Item><Form.Item name="mode" label="编排模式" rules={[{ required: true }]}><Select options={[['sequential', '顺序协作'], ['concurrent', '并行协作'], ['handoff', '接力协作'], ['react', 'REACT 反思循环']].map(([value, label]) => ({ value, label }))} /></Form.Item><Form.Item name="worker_ids" label="参与员工" rules={[{ required: true, message: '至少选择一名员工' }]}><Select mode="multiple" options={workers.filter(item => item.enabled).map(item => ({ value: item.worker_id, label: `${item.name} (${item.worker_id})` }))} /></Form.Item><Button htmlType="submit" type="primary" loading={submitting} icon={<PlayCircleOutlined />}>继续执行</Button></Form></Card></>
}

function History() { const [runs, setRuns] = useState<Orchestration[]>(); useEffect(() => { api.listRuns().then(setRuns) }, []); if (!runs) return <Skeleton active />; return <><div className="page-heading"><div><Typography.Title level={2}>任务历史</Typography.Title><Typography.Text type="secondary">运行记录与审计快照</Typography.Text></div></div><List className="history" dataSource={runs} locale={{ emptyText: '尚无协作任务' }} renderItem={run => <List.Item actions={[<Link key="open" to={`/tasks/${run.orchestration_id}`}>查看</Link>, <Link key="continue" to={`/tasks/${run.orchestration_id}/continue`}>继续</Link>]}><List.Item.Meta title={<Space><Status value={run.status} /><Typography.Text strong>{run.goal}</Typography.Text></Space>} description={`${run.orchestration_id} · ${run.mode}${run.continued_from ? ` · 续自 ${run.continued_from}` : ''}`} /></List.Item>} /></> }

function SkillAdmin() {
  const [skills, setSkills] = useState<Skill[]>(); const [preview, setPreview] = useState<SkillPreview>(); const [form] = Form.useForm(); const [notice, contextHolder] = message.useMessage()
  const refresh = () => api.skills().then(setSkills)
  useEffect(() => { void refresh() }, [])
  const create = async (values: { name: string; content: string }) => { try { await api.createSkill({ ...values, source: 'inline' }); form.resetFields(); refresh(); notice.success('Skill 已入库') } catch (error) { notice.error(error instanceof Error ? error.message : '保存失败') } }
  const inspect = async (name: string) => { try { setPreview(await api.previewSkill(name)) } catch (error) { notice.error(error instanceof Error ? error.message : '预览失败') } }
  const remove = async (name: string) => { await api.deleteSkill(name); if (preview?.name === name) setPreview(undefined); refresh() }
  if (!skills) return <Skeleton active />
  return <>{contextHolder}<div className="page-heading"><div><Typography.Title level={2}>Skill 库</Typography.Title><Typography.Text type="secondary">外部内容以不可信上下文注入，保存前按 UC 规范解析</Typography.Text></div></div><div className="admin-layout"><Card title="新建 Inline Skill" className="form-panel"><Form form={form} layout="vertical" onFinish={create}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input placeholder="report-style" /></Form.Item><Form.Item name="content" label="SKILL.md" rules={[{ required: true }]}><Input.TextArea rows={11} placeholder={'---\nname: report-style\ndescription: 报告规范\n---\n\n正文'} /></Form.Item><Button htmlType="submit" type="primary">保存 Skill</Button></Form></Card><Card title="已登记 Skill" className="catalog-card"><List dataSource={skills} locale={{ emptyText: '尚无 Skill' }} renderItem={skill => <List.Item actions={[<Button key="preview" type="link" onClick={() => inspect(skill.name)}>解析预览</Button>, <Button key="delete" type="text" danger icon={<DeleteOutlined />} onClick={() => remove(skill.name)} />]}><List.Item.Meta title={skill.name} description={skill.description} /></List.Item>} /></Card></div>{preview && <Card title={`解析预览 · ${preview.name}`} className="preview-card"><Typography.Paragraph>{preview.description}</Typography.Paragraph><Typography.Text type="secondary">digest: {preview.digest}</Typography.Text><pre>{preview.body}</pre></Card>}</>
}

function McpAdmin() {
  const [servers, setServers] = useState<McpServer[]>(); const [result, setResult] = useState<string>(); const [editing, setEditing] = useState<string>(); const [form] = Form.useForm(); const [notice, contextHolder] = message.useMessage()
  const refresh = () => api.mcpServers().then(setServers)
  useEffect(() => { void refresh() }, [])
  const save = async (values: McpServer) => { try { if (editing) await api.updateMcpServer(editing, { ...values, args: values.args ?? [], allowed_tools: values.allowed_tools ?? [], blocked_tools: values.blocked_tools ?? [] }); else await api.createMcpServer({ ...values, command: values.command ?? '' }); form.resetFields(); setEditing(undefined); refresh(); notice.success(editing ? 'MCP Server 已更新' : 'MCP Server 已登记') } catch (error) { notice.error(error instanceof Error ? error.message : '保存失败') } }
  const probe = async (name: string) => { const response = await api.probeMcpServer(name); setResult(`${name}: ${response.message}`) }
  const edit = (server: McpServer) => { setEditing(server.name); form.setFieldsValue(server) }
  const remove = async (name: string) => { try { await api.deleteMcpServer(name); if (editing === name) { setEditing(undefined); form.resetFields() }; refresh(); notice.success('MCP Server 已删除') } catch (error) { notice.error(error instanceof Error ? error.message : '删除失败') } }
  if (!servers) return <Skeleton active />
  return <>{contextHolder}<div className="page-heading"><div><Typography.Title level={2}>MCP Server 目录</Typography.Title><Typography.Text type="secondary">维护端点与 transport 配置，运行时探针仅在已配置 adapter 时执行</Typography.Text></div></div><div className="admin-layout"><Card title={editing ? `编辑 MCP Server · ${editing}` : '登记 MCP Server'} className="form-panel"><Form form={form} layout="vertical" initialValues={{ transport: 'streamable_http', args: [], allowed_tools: [], blocked_tools: [] }} onFinish={save}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input disabled={Boolean(editing)} placeholder="enterprise-ticket" /></Form.Item><Form.Item name="transport" label="Transport"><Select options={[{ value: 'streamable_http', label: 'STREAMABLE_HTTP' }, { value: 'stdio', label: 'STDIO' }, { value: 'websocket', label: 'WEBSOCKET' }]} /></Form.Item><Form.Item name="url" label="URL"><Input placeholder="https://hub.example/mcp" /></Form.Item><Space><Button htmlType="submit" type="primary">{editing ? '保存修改' : '登记服务'}</Button>{editing && <Button onClick={() => { setEditing(undefined); form.resetFields() }}>取消</Button>}</Space></Form></Card><Card title="已登记 Server" className="catalog-card"><List dataSource={servers} locale={{ emptyText: '尚无 MCP Server' }} renderItem={server => <List.Item actions={[<Button key="probe" onClick={() => probe(server.name)}>连通性测试</Button>, <Button key="edit" type="link" onClick={() => edit(server)}>编辑</Button>, <Popconfirm key="delete" title="删除该 MCP Server？" description="已绑定员工时不能删除。" onConfirm={() => remove(server.name)}><Button type="text" danger icon={<DeleteOutlined />} /></Popconfirm>]}><List.Item.Meta title={<Space>{server.name}<Tag color="cyan">{server.transport}</Tag></Space>} description={server.url || server.command || '未配置端点'} /></List.Item>} /></Card></div>{result && <Alert className="approval-alert" type="info" showIcon message="Probe 结果" description={result} />}</>
}

function WorkerAdmin() {
  const navigate = useNavigate(); const { workerId } = useParams(); const editing = Boolean(workerId); const [form] = Form.useForm(); const [notice, contextHolder] = message.useMessage(); const [probe, setProbe] = useState<string>(); const [servers, setServers] = useState<McpServer[]>([])
  useEffect(() => { api.mcpServers().then(setServers).catch(() => setServers([])); if (workerId) api.worker(workerId).then(worker => form.setFieldsValue({ ...worker, capabilities: worker.capabilities.join(', ') })).catch(error => notice.error(error instanceof Error ? error.message : '加载员工失败')) }, [form, notice, workerId])
  const save = async (values: { worker_id: string; name: string; description: string; capabilities?: string; runtime_name: string; mcp_server_names: string[] }) => { try { const payload = { worker_id: values.worker_id, name: values.name, description: values.description, runtime_name: values.runtime_name, capabilities: (values.capabilities ?? '').split(',').map(item => item.trim()).filter(Boolean), mcp_server_names: values.mcp_server_names ?? [] }; const worker = editing ? await api.updateWorker(workerId!, payload) : await api.createWorker(payload); const response = await api.probeWorker(worker.worker_id); setProbe(response.message); notice.success(editing ? '员工已更新并通过运行时校验' : '员工已注册并通过运行时校验'); if (!editing) form.resetFields() } catch (error) { notice.error(error instanceof Error ? error.message : '保存失败') } }
  return <>{contextHolder}<div className="page-heading"><div><Typography.Title level={2}>{editing ? '编辑数字员工' : '注册数字员工'}</Typography.Title><Typography.Text type="secondary">为员工显式选择运行时与允许使用的 MCP Server</Typography.Text></div><Button onClick={() => navigate('/workers')}>返回目录</Button></div><Card className="worker-form"><Form form={form} layout="vertical" initialValues={{ runtime_name: 'offline-contract', mcp_server_names: [] }} onFinish={save}><Form.Item name="worker_id" label="Worker ID" rules={[{ required: true }]}><Input disabled={editing} placeholder="briefing" /></Form.Item><Form.Item name="name" label="显示名称" rules={[{ required: true }]}><Input placeholder="简报助手" /></Form.Item><Form.Item name="description" label="职责" rules={[{ required: true }]}><Input.TextArea rows={4} /></Form.Item><Form.Item name="runtime_name" label="运行时" rules={[{ required: true }]}><Select options={[{ value: 'offline-contract', label: '离线流程演示（不调用模型或 MCP）' }, { value: 'openai-compatible', label: 'OpenAI Compatible（无 MCP）' }, { value: 'mcp-openai-compatible', label: 'OpenAI Compatible + 单个 HTTP MCP' }, { value: 'agentscope-mcp', label: 'AgentScope + MCP' }, { value: 'langgraph-mcp', label: 'LangGraph + MCP' }]} /></Form.Item><Form.Item name="mcp_server_names" label="绑定 MCP Server"><Select mode="multiple" placeholder="仅允许员工使用这里显式选择的服务" options={servers.map(server => ({ value: server.name, label: `${server.name} (${server.transport})` }))} /></Form.Item><Form.Item name="capabilities" label="能力标签"><Input placeholder="briefing, reporting" /></Form.Item><Button htmlType="submit" type="primary" icon={<PlusOutlined />}>{editing ? '保存并校验' : '注册并校验'}</Button></Form>{probe && <Alert className="approval-alert" type="success" showIcon message="运行时验证" description={probe} />}</Card></>
}

function Shell() { return <Layout className="shell"><Sider width={236} className="sidebar"><div className="brand"><span className="brand-mark">DW</span><div>Digital<br />Workforce</div></div><nav><NavLink to="/workers"><TeamOutlined />员工目录</NavLink><NavLink to="/tasks/new"><PlayCircleOutlined />发起任务</NavLink><NavLink to="/tasks"><UnorderedListOutlined />任务历史</NavLink><NavLink to="/admin/workers/new"><PlusOutlined />注册员工</NavLink><NavLink to="/admin/skills"><BookOutlined />Skill 库</NavLink><NavLink to="/admin/mcp-hub"><ApiOutlined />MCP 目录</NavLink></nav><div className="sidebar-foot"><FileTextOutlined /> 企业协作平台</div></Sider><Layout><Header className="topbar"><Typography.Text>运营控制台</Typography.Text><Tag color="green">系统就绪</Tag></Header><Content className="content"><Routes><Route path="/" element={<Workers />} /><Route path="/workers" element={<Workers />} /><Route path="/tasks/new" element={<NewTask />} /><Route path="/tasks/:id/continue" element={<ContinueTask />} /><Route path="/tasks/:id" element={<TaskDetail />} /><Route path="/tasks" element={<History />} /><Route path="/admin/workers/new" element={<WorkerAdmin />} /><Route path="/admin/workers/:workerId/edit" element={<WorkerAdmin />} /><Route path="/admin/skills" element={<SkillAdmin />} /><Route path="/admin/mcp-hub" element={<McpAdmin />} /></Routes></Content></Layout></Layout> }

export default function App() { return <ConfigProvider theme={{ token: { colorPrimary: '#116466', borderRadius: 6, fontFamily: 'Georgia, Noto Serif SC, serif' } }}><AntApp><BrowserRouter><Shell /></BrowserRouter></AntApp></ConfigProvider> }

createRoot(document.getElementById('root')!).render(<App />)
